apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai
spec:
  type: conversation.openai
  version: v1
  metadata:
  - name: key
    value: "<KEY>"
  - name: model
    value: gpt-4.1-2025-04-14
  - name: endpoint
    value: "https://<URL>.openai.azure.com/"
  - name: apiType
    value: azure
  - name: apiVersion
    value: 2024-12-01-preview
